[package]
name = "stow_ffi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "C-ABI and Foreign Function Interface (FFI) bindings for mobile (Android/iOS) and Flutter integrations."

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
stow_core = { path = "../stow_core" }
serde_json = { workspace = true }
libc = "0.2"
